Script split and singature refactor
Separate script/sign
Separate CScriptCompressor
Separate script/standard
Separate script/interpreter
Move CScript class and dependencies to script/script
Rename script.h/.cpp to scriptutils.h/.cpp

Rename scriptutils.o to wallet_ismine.o
Move CAffectedKeysVisitor to wallet.cpp (remove ExtractAffectedKeys)
Move scriptutils.o to wallet

Move CTxDestination from script/script to script/standard

Remove unused function main:VerifySignature
Remove CScriptCheck::nHashType (was always 0)
Don't pass nHashType to VerifyScript
Don't pass nHashType to EvalScript nor CheckSig

Abstract out SignatureChecker
Make signature cache optional
Replace SCRIPT_VERIFY_NOCACHE by flag directly to checker

Remove unused function StackString() and class CCoins;

Discover some missing includes

Broken addresses on command line no longer trigger testnet.

When passing a bitcoin: URI on the command line, invalid addresses do not incorrectly send the
user to the test network.

Bugfix: bitcoin-tx: scriptPubKey may be null, so accept outscript=<n>:

bitcoin-tx: fix build warnings

Cleans up a bunch of:
warning: missing braces around initializer for ‘const<anonymous struct>’

bitcoin-tx: Accept input via stdin. Add input handling to tests.

fix compilation error in core_io.h

- error: 'vector' in namespace 'std' does not name a type
- add <vector> include in core_io.h
- remove <vector> includes from core_read.cpp and core_write.cpp

Clarify 'compressed nor uncompressed' error message

script.h: set_vch() should shift a >32 bit value

Source: http://www.viva64.com/en/b/0268/

Declare SignatureHash() in script.h

Remove unused CKeyStoreIsMineVisitor

Relax IsStandard rules for pay-to-script-hash transactions

Relax the AreInputsStandard() tests for P2SH transactions --
allow any Script in a P2SH transaction to be relayed/mined,
as long as it has 15 or fewer signature operations.

Rationale: https://gist.github.com/gavinandresen/88be40c141bc67acb247

I don't have an easy way to test this, but the code changes are
straightforward and I've updated the AreInputsStandard unit tests.

Make SCRIPT_VERIFY_STRICTENC compatible with BIP62

* Delete canonical_tests.cpp, and move the tests to script_tests.cpp.
* Split off SCRIPT_VERIFY_DERSIG from SCRIPT_VERIFY_STRICTENC (the BIP62 part of it).
* Change signature STRICTENC/DERSIG semantics to fail the script entirely rather than the CHECKSIG result (softfork safety, and BIP62 requirement).
* Add many autogenerated tests for several odd cases.
* Mention specific BIP62 rules in the script verification flags.

Reinitializing list's begin iterator after few elements were erased f…

…rom the head

script: Fix reference into empty vector run time exception

Edit by laanwj: `begin_ptr(sourcedata) + sourcedata.size()` -> `end_ptr(sourcedata)`

script: don't read past the end

Print input index when signature validation fails, to aid debugging.

Don't return an address for invalid pubkeys

base58: add paranoid return value checks

Fixing out of bounds error in GetKey()

BTC Commit(s):
e088d65acbb181220b64a45a2a62bb79c0e40304
9294a4bbe7ec067a45905b6e693414ad7d3b5669
c4408a6c8534a36711557028a69314024cbc1bbe
da03e6ed7c380d8942592626b9677579267f86fd
cbd22a50c4b3d2d0f133c5f8d34c9c7aca9c7f4f
86dbeea2cdd5749374c98afea3e4f5f49817f746
c1e433b717fbc26a74ca395771076b203630a5a2
8b59a3d36626085db79db2874ae76272b2b42f25
0d2fa14a3434fb259319aedec0124df305e652c0
0be990ba34110184c8a5a2c04094311dab5cd84c
358562b65189dce982ad30a1c158606a540e9bcb
ce3649fb61b2b421aa4e36ab107e5f2f9838378b
2b23a87599b7d28e86ca193e7b52f429bcdf144f
6dcfda2dc48bee2148acd571dce7d3f09608d7a2
c7829ea797c840dda7888ee860a50b7a3308069d
5c1e798a8e9df15f8fbd120e57fc67e585f13843
e790c370b5971dd096d1bbfd55960ccf71b7594a
8d5e5102f6f80c037b6bbc2985b778fd40c80d1c
53efb09e4ceaa0ccb4e6271387f5013fe5e1ec75
e84843c0dbb9cb853b912c09858b01c5c9302b09
15ef1b905b3b468a024b8d5b20c94d80d3c4296a
616c24307f4f18d7dbd603b5d9688904f2d74210
fb14452c6cadb8d977c405dddb0a94115250d7c4
1b73d36b2c71c92044012dc736215bf95f2e908b
8e44f2e00a14e1d12f898ae54f77e9de228d206f
6fd59ee897e9dc9b021440cbb738186dbf3a3e98
f5745fa52a66ab9ba976e06de4881e981d9aa6b4
54e658f249f8b2a2cbf7dbe2bab9749faa91c611
7f3b4e95695d50a4970e6eb91faa956ab276f161
9df9cf5a9f5f56261b0b226dec6249f9dfbefed6
cda45b5131c3546b870d8cea3191fb29df182b27
219372f1dd504b0e187da88e3c0adf25a7e6b8d2
be6d87aa60c1aca886b557901a493119c2aac024
f74fc9b22d7f39e36d0cbf80f5c06958c516c8ec
9d7cd4c598edfff12f1f80629c9149b3f1cf75a6
88df548dde280efac8eb33520f8192885455bc03
6f3ae9b5df1a65c47aeb221afcf079b0fae566d4