Make GetAvailableCredit run GetHash() only once per transaction.
This makes the first getbalance/getinfo 63x faster on my wallet.


[Qt] small cleanup of coincontroldialog

- use a little more Qt-style
- check for NULL pointers first and return in updateView()
- small space and formating changes


remove an assignment which is never used.


Bugfix: configure: Look in libx32 subdirectory for boost libraries


build: Sync ax_boost_base.m4 with upstream.

This should fix 32bit boost detection on Ubuntu Saucy+. Fixes #3945.


[Qt] importwallet progress


build: fix: remove error output

while git not found in path, error is output to console.


VERSION obtained from source instead of the previous git tag.

Drawback: The version string is no longer a valid git identifier.
          For this reason the 'g' short hash prefix has been removed.

Exception: When building directly from a tag this behaves exactly like the previous behavior.
           This allows formatting release versions with precision     i.e. v0.9.2
           This also allows arbitrary topicbranch names               i.e. v0.9.1-glibc-compat


ui: Check for !pixmap() before trying to export QR code

Adds null pointer checks as well as prevents the Save/Copy context
menu from appearing at all if no image is shown.

Fixes issue #4140


Remove forward declaration for non-existent class CCoinsDB

Found by stephenreed on #bitcoin.dev.

BTC Commit(s):
a60ab0ba89289433563c4c0993904acbca8c99ff
d34b958406869018dec6302ae2ed3aa062ea7516
fbf617a5f1a51bce59e023dbada9a4dd050e6c35
c0e0b05aec621f154e811c0ff2ad4bded4ea7262
13a2283a6d33fd844017fe8ab3ed660ea1eb7be7
bb1f1c90d669649fe80b92094718a9173586eb43
b1f0be0a05aca81e564139472206dee72410976e
3d20cd5f61fff33fe5fffd6efddf2c942c8dd2f9
9d558e1c18a29bbccec802829f9b8b65fb4101a1
a48355dc44e8b86c2fc9f8b7973ac9e81a295be7